version: '3'
services:
  frontend:
    image: x/client:local
    build:
      context: ./client
    ports:
      - '3000:3000'
    depends_on:
      - generator
      - redis

  generator:
    image: x/backend:local
    build:
      context: ./generator-service
    ports:
      - '4000:4000'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
